[project]
name = "proyecto-drf-tomas-benavidez"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tomas benavidez", email = "t.benavidez@itecriocuarto.org.ar" }
]
requires-python = ">=3.12"
dependencies = [
    "django>=6.1",
    "djangorestframework>=3.18.0",
]
